In [3]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

college_df = pd.read_csv(r'F:\simplilearn AI master course\Live Classes\Machine Learning\Shared Google Drive\Week2-20200725T111145Z-001\Week2\Tuesday\dataset\College_Classification\Lesson 6-Supervised Learning-Classification\College.csv')
college_df.head()

Private  Apps  Accept  Enroll  Top10perc  Top25perc  F.Undergrad  \
0     Yes  1660    1232     721         23         52         2885   
1     Yes  2186    1924     512         16         29         2683   
2     Yes  1428    1097     336         22         50         1036   
3     Yes   417     349     137         60         89          510   
4     Yes   193     146      55         16         44          249   

   P.Undergrad  Outstate  Room.Board  Books  Personal  PhD  Terminal  \
0          537      7440        3300    450      2200   70        78   
1         1227     12280        6450    750      1500   29        30   
2           99     11250        3750    400      1165   53        66   
3           63     12960        5450    450       875   92        97   
4          869      7560        4120    800      1500   76        72   

   S.F.Ratio  perc.alumni  Expend  Grad.Rate  
0       18.1           12    7041         60  
1       12.2           16   10527         56  
2       12.9           30    8735         54  
3        7.7           37   19016         59  
4       11.9            2   10922         15

In [4]:
college_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 777 entries, 0 to 776
Data columns (total 18 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Private      777 non-null    object 
 1   Apps         777 non-null    int64  
 2   Accept       777 non-null    int64  
 3   Enroll       777 non-null    int64  
 4   Top10perc    777 non-null    int64  
 5   Top25perc    777 non-null    int64  
 6   F.Undergrad  777 non-null    int64  
 7   P.Undergrad  777 non-null    int64  
 8   Outstate     777 non-null    int64  
 9   Room.Board   777 non-null    int64  
 10  Books        777 non-null    int64  
 11  Personal     777 non-null    int64  
 12  PhD          777 non-null    int64  
 13  Terminal     777 non-null    int64  
 14  S.F.Ratio    777 non-null    float64
 15  perc.alumni  777 non-null    int64  
 16  Expend       777 non-null    int64  
 17  Grad.Rate    777 non-null    int64  
dtypes: float64(1), int64(16), object(1)
memory usage: 

In [5]:
college_df.isnull().sum()

Private        0
Apps           0
Accept         0
Enroll         0
Top10perc      0
Top25perc      0
F.Undergrad    0
P.Undergrad    0
Outstate       0
Room.Board     0
Books          0
Personal       0
PhD            0
Terminal       0
S.F.Ratio      0
perc.alumni    0
Expend         0
Grad.Rate      0
dtype: int64

In [6]:
college_df.describe()

Apps        Accept       Enroll   Top10perc   Top25perc  \
count    777.000000    777.000000   777.000000  777.000000  777.000000   
mean    3001.638353   2018.804376   779.972973   27.558559   55.796654   
std     3870.201484   2451.113971   929.176190   17.640364   19.804778   
min       81.000000     72.000000    35.000000    1.000000    9.000000   
25%      776.000000    604.000000   242.000000   15.000000   41.000000   
50%     1558.000000   1110.000000   434.000000   23.000000   54.000000   
75%     3624.000000   2424.000000   902.000000   35.000000   69.000000   
max    48094.000000  26330.000000  6392.000000   96.000000  100.000000   

        F.Undergrad   P.Undergrad      Outstate   Room.Board        Books  \
count    777.000000    777.000000    777.000000   777.000000   777.000000   
mean    3699.907336    855.298584  10440.669241  4357.526384   549.380952   
std     4850.420531   1522.431887   4023.016484  1096.696416   165.105360   
min      139.000000      1.000000   2340.000000  1780.000000    96.000000   
25%      992.000000     95.000000   7320.000000  3597.000000   470.000000   
50%     1707.000000    353.000000   9990.000000  4200.000000   500.000000   
75%     4005.000000    967.000000  12925.000000  5050.000000   600.000000   
max    31643.000000  21836.000000  21700.000000  8124.000000  2340.000000   

          Personal         PhD    Terminal   S.F.Ratio  perc.alumni  \
count   777.000000  777.000000  777.000000  777.000000   777.000000   
mean   1340.642214   72.660232   79.702703   14.089704    22.743887   
std     677.071454   16.328155   14.722359    3.958349    12.391801   
min     250.000000    8.000000   24.000000    2.500000     0.000000   
25%     850.000000   62.000000   71.000000   11.500000    13.000000   
50%    1200.000000   75.000000   82.000000   13.600000    21.000000   
75%    1700.000000   85.000000   92.000000   16.500000    31.000000   
max    6800.000000  103.000000  100.000000   39.800000    64.000000   

             Expend  Grad.Rate  
count    777.000000  777.00000  
mean    9660.171171   65.46332  
std     5221.768440   17.17771  
min     3186.000000   10.00000  
25%     6751.000000   53.00000  
50%     8377.000000   65.00000  
75%    10830.000000   78.00000  
max    56233.000000  118.00000

In [8]:
print(college_df.shape)
print(college_df['Private'].value_counts())

(777, 18)
Yes    565
No     212
Name: Private, dtype: int64


In [27]:
x = college_df.iloc[:,1:]
y = college_df.iloc[:,0]
x

Apps  Accept  Enroll  Top10perc  Top25perc  F.Undergrad  P.Undergrad  \
0     1660    1232     721         23         52         2885          537   
1     2186    1924     512         16         29         2683         1227   
2     1428    1097     336         22         50         1036           99   
3      417     349     137         60         89          510           63   
4      193     146      55         16         44          249          869   
..     ...     ...     ...        ...        ...          ...          ...   
772   2197    1515     543          4         26         3089         2029   
773   1959    1805     695         24         47         2849         1107   
774   2097    1915     695         34         61         2793          166   
775  10705    2453    1317         95         99         5217           83   
776   2989    1855     691         28         63         2988         1726   

     Outstate  Room.Board  Books  Personal  PhD  Terminal  S.F.Ratio  \
0        7440        3300    450      2200   70        78       18.1   
1       12280        6450    750      1500   29        30       12.2   
2       11250        3750    400      1165   53        66       12.9   
3       12960        5450    450       875   92        97        7.7   
4        7560        4120    800      1500   76        72       11.9   
..        ...         ...    ...       ...  ...       ...        ...   
772      6797        3900    500      1200   60        60       21.0   
773     11520        4960    600      1250   73        75       13.3   
774      6900        4200    617       781   67        75       14.4   
775     19840        6510    630      2115   96        96        5.8   
776      4990        3560    500      1250   75        75       18.1   

     perc.alumni  Expend  Grad.Rate  
0             12    7041         60  
1             16   10527         56  
2             30    8735         54  
3             37   19016         59  
4              2   10922         15  
..           ...     ...        ...  
772           14    4469         40  
773           31    9189         83  
774           20    8323         49  
775           49   40386         99  
776           28    4509         99  

[777 rows x 17 columns]

In [28]:
from sklearn.preprocessing import LabelEncoder

lbl = LabelEncoder()
y = lbl.fit_transform(y)

In [29]:
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(543, 17)
(543,)
(234, 17)
(234,)


In [30]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

svc = SVC()
svc.fit(x_train,y_train)
y_pred = svc.predict(x_test)

print("accuracy_score = ",accuracy_score(y_pred,y_test),"\n")
print("confusion_matrix : ")
print(confusion_matrix(y_pred,y_test),"\n")
print("classification_report : ")
print(classification_report(y_pred,y_test))

accuracy_score =  0.7350427350427351 

confusion_matrix : 
[[  0   0]
 [ 62 172]] 

classification_report : 
              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.74      0.85       234

    accuracy                           0.74       234
   macro avg       0.50      0.37      0.42       234
weighted avg       1.00      0.74      0.85       234



In [31]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x = scaler.fit_transform(x)

In [32]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size = 0.3)

print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

(543, 17)
(543,)
(234, 17)
(234,)


In [33]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

svc = SVC()
svc.fit(x_train,y_train)
y_pred = svc.predict(x_test)

print("accuracy_score = ",accuracy_score(y_pred,y_test),"\n")
print("confusion_matrix : ")
print(confusion_matrix(y_pred,y_test),"\n")
print("classification_report : ")
print(classification_report(y_pred,y_test))

accuracy_score =  0.9145299145299145 

confusion_matrix : 
[[ 61   1]
 [ 19 153]] 

classification_report : 
              precision    recall  f1-score   support

           0       0.76      0.98      0.86        62
           1       0.99      0.89      0.94       172

    accuracy                           0.91       234
   macro avg       0.88      0.94      0.90       234
weighted avg       0.93      0.91      0.92       234



In [40]:
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis


lda = LinearDiscriminantAnalysis(n_components = 2)
x_train = lda.fit_transform(x_train,y_train)
x_test = lda.transform(x_test)

In [41]:
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

svc = SVC()
svc.fit(x_train,y_train)
y_pred = svc.predict(x_test)

print("accuracy_score = ",accuracy_score(y_pred,y_test),"\n")
print("confusion_matrix : ")
print(confusion_matrix(y_pred,y_test),"\n")
print("classification_report : ")
print(classification_report(y_pred,y_test))

accuracy_score =  0.9358974358974359 

confusion_matrix : 
[[ 68   3]
 [ 12 151]] 

classification_report : 
              precision    recall  f1-score   support

           0       0.85      0.96      0.90        71
           1       0.98      0.93      0.95       163

    accuracy                           0.94       234
   macro avg       0.92      0.94      0.93       234
weighted avg       0.94      0.94      0.94       234



In [44]:
from sklearn.model_selection import GridSearchCV

grid_params = {'C':[0.1,1,10,100],'gamma':[1,0.1,0.01,0.001]}
grid = GridSearchCV(SVC(), grid_params, refit = True, verbose = 2)
grid.fit(x_train,y_train)

Fitting 3 folds for each of 16 candidates, totalling 48 fits
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.0s
[CV] C=0.1, gamma=1 ..................................................
[CV] ................................... C=0.1, gamma=1, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.0s
[CV] C=0.1, gamma=0.1 ................................................
[CV] ................................. C=0.1, gamma=0.1, total=   0.0s
[CV] C=0.1, gamma=0.01 ...............................................
[CV] ...........

[Parallel(n_jobs=1)]: Using backend SequentialBackend with 1 concurrent workers.
[Parallel(n_jobs=1)]: Done   1 out of   1 | elapsed:    0.0s remaining:    0.0s


[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   0.0s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   0.0s
[CV] C=100, gamma=0.1 ................................................
[CV] ................................. C=100, gamma=0.1, total=   0.0s
[CV] C=100, gamma=0.01 ...............................................
[CV] ................................ C=100, gamma=0.01, total=   0.0s
[CV] C=100, gamma=0.01 ...............................................
[CV] ................................ C=100, gamma=0.01, total=   0.0s
[CV] C=100, gamma=0.01 ...............................................
[CV] ................................ C=100, gamma=0.01, total=   0.0s
[CV] C=100, gamma=0.001 ..............................................
[CV] ............................... C=100, gamma=0.001, total=   0.0s
[CV] C

[Parallel(n_jobs=1)]: Done  48 out of  48 | elapsed:    0.1s finished


GridSearchCV(cv='warn', error_score='raise-deprecating',
             estimator=SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
                           decision_function_shape='ovr', degree=3,
                           gamma='auto_deprecated', kernel='rbf', max_iter=-1,
                           probability=False, random_state=None, shrinking=True,
                           tol=0.001, verbose=False),
             iid='warn', n_jobs=None,
             param_grid={'C': [0.1, 1, 10, 100],
                         'gamma': [1, 0.1, 0.01, 0.001]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=2)

In [45]:
grid_pred = grid.predict(x_test)
print("accuracy_score = ",accuracy_score(grid_pred,y_test))
print("confusion_matrix : ")
print(confusion_matrix(grid_pred,y_test),"\n")
print("classification_report : ")
print(classification_report(grid_pred,y_test))

accuracy_score =  0.9358974358974359
confusion_matrix : 
[[ 68   3]
 [ 12 151]] 

classification_report : 
              precision    recall  f1-score   support

           0       0.85      0.96      0.90        71
           1       0.98      0.93      0.95       163

    accuracy                           0.94       234
   macro avg       0.92      0.94      0.93       234
weighted avg       0.94      0.94      0.94       234

